version: '3'
services:
        mysql:
                build: ./mysql
                ports:
                - "3306:3306"
                restart: always
                environment: 
                        MYSQL_ROOT_PASSWORD: "mysqlpass"
                        MYSQL_USER:  "root"
                        MYSQL_DATABASE: "buzzinga"
        web:
                depends_on:
                -  mysql
                build: ./webapp
                ports:
                - "5000:5000"
                volumes:
                - ./webapp:/buzzinga
        redis:
                depends_on:
                - mysql 
                image: "redis:alpine"
